apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uagent.fullname" . }}-cfg
data:
  {{- if .Values.agent.name }}
  UAGENT_NAME: {{ .Values.agent.name | quote }}
  {{- end }}
  {{- if .Values.agent.type }}
  UAGENT_TYPE: {{ .Values.agent.type | quote }}
  {{- end }}
