name: Integration Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  integration:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'integrations')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python and dependencies
        run: |
          sudo apt-get install python3 python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install requests

      - name: Run script with PR number
        run: |
          source venv/bin/activate
          python notifier.py "${{ github.event.pull_request.number }}" "${{ secrets.SLACK_TOKEN }}" "${{ secrets.CHANNEL_ID }}"
          